version: '3.8'

services:
  splitter:
    build:
      context: .
      dockerfile: src/services/splitter/Dockerfile
    container_name: splitter_service
    environment:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}
  splitter_v2:
    build:
      context: .
      dockerfile: src/services/splitter/Dockerfile
    container_name: splitter_service_v2
    environment:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_KEY: ${SUPABASE_KEY}

